// This file contains the backend API call-functions
class BackendAPI {
  // Constans which store the URLs of the database-tables
  static USER_TABLE = "http://localhost:8000/students4students/register";
  static DEGREE_TABLE = "http://localhost:8000/students4students/degrees";

  // This API function sends Data (structured by an object) via a POST request to the backend
  static sendObjectDataToBackend<Type>(obj: Type, url: string) {
    fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(obj),
    })
      .then((res) => res.json())
      .then((data) => {
        console.log(data);
      })
      .catch((err) => console.log(err));
  }
  //Generated by github-Copilot, as of now, no knowledge about the backend connection

  static async getDataFromBackend(url: string): Promise<any> {
    try {
      const response = await fetch(url);
      const data = await response.json();
      return data;
    } catch (err) {
      console.error(err);
      throw err; // You can handle errors in the calling code
    }
  }
}

export default BackendAPI;
