import { useState } from "react";
import "../css/Loginstyles.css";
import "./interfaces";
import BackendAPI from "./BackendAPI";

function RegisterPage() {
  //--------------------/Password-Handling--------------------
  // handling the password input
  // if the first entry is not the same as the second entry, the user gets an alert
  const [firstEntryPassword, setfirstEntryPassword] = useState<string>("");
  const [secondEntryPassword, setsecondEntryPassword] = useState<string>("");

  function handleFirstEntryPasswordChange(event: any) {
    setfirstEntryPassword(event.target.value);
  }

  function handleSecondEntryPasswordChange(event: any) {
    setsecondEntryPassword(event.target.value);
  }

  function checkPasswords() {
    if (firstEntryPassword !== secondEntryPassword) {
      alert("Passwords do not match");
      return false;
    }
    return true;
  }
  //--------------------Password-Handling/--------------------

  //--------------------/Email-Check--------------------
  // handling the first step of email verification
  // if the email is not from the dhbw, the user gets an alert
  const [email, setEmail] = useState<string>("");
  function handleEmailChange(event: any) {
    setEmail(event.target.value);
  }

  function checkEmail() {
    if (!email.includes("@lehre.dhbw-stuttgart.de")) {
      alert("Please enter a valid DHBW email");
      return false;
    }
    return true;
  }

  //--------------------Email-Check/--------------------

  //--------------------/Degree-Database-Check-----------------
  //compares the User-input to the Degree-Database
  const [degrees, setDegrees] = useState<Degree[]>([]);
  const [userDegree, setUserDegree] = useState<string>("");
  function handleDegreeChange(event: any) {
    setUserDegree(event.target.value);
  }
  // checks if the user degree input is in the degree database
  async function checkDegree() {
    setDegrees(await BackendAPI.getDataFromBackend(BackendAPI.DEGREE_TABLE));
    console.log(degrees);
    if (false) {
      // generated by github copilot idk if it works (degrees.some? whats that? Answer: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/some)
      alert("Please enter an existing degree");
      return false;
    }
    return true;
  }
  //--------------------Degree-Database-Check/-----------------

  //--------------------/Main-functionality-------------------
  // handling the user input when pressing the register button

  // all user data is stored in the following variables and later in a User object
  const [username, setUsername] = useState<string>("");
  const [first_name, setFirst_name] = useState<string>("");
  const [surname, setSurname] = useState<string>("");
  const [age, setAge] = useState<string>("");
  const [semester, setSemester] = useState<string>("");
  const [partner_company, setPartner_company] = useState<string>("");
  //email, degree and password are already defined above

  function handlingUserInput() {
    if (checkPasswords() && checkEmail()) {
      console.log(checkDegree());
      //send user data to backend
      const newUser: User = {
        first_name: first_name,
        surname: surname,
        age: parseInt(age),
        degree: userDegree,
        semester: parseInt(semester),
        partner_company: partner_company,
        email: email,
        username: username,
        password: firstEntryPassword,
      };
      BackendAPI.sendObjectDataToBackend<User>(newUser, BackendAPI.USER_TABLE);
    }
  }
  //--------------------Main-functionality/-------------------
  return (
    <>
      <h1>Registerpage</h1>
      <br />
      <div className="login-flex">
        <h3>Register</h3>
        <input
          type="text"
          placeholder="First Name"
          onChange={(e) => setFirst_name(e.target.value)}
        />
        <br />
        <input
          type="text"
          placeholder="Surname"
          onChange={(e) => setSurname(e.target.value)}
        />
        <br />
        <input
          type="text"
          placeholder="Age"
          onChange={(e) => setAge(e.target.value)}
        />
        <br />
        <input type="text" placeholder="Degree" onChange={handleDegreeChange} />
        <br />
        <input
          type="text"
          placeholder="Semester"
          onChange={(e) => setSemester(e.target.value)}
        />
        <br />
        <input
          type="text"
          placeholder="Partner Company"
          onChange={(e) => setPartner_company(e.target.value)}
        />
        <br />
        <input type="text" placeholder="Email" onChange={handleEmailChange} />
        <br />
        <input
          type="text"
          placeholder="Username"
          onChange={(e) => setUsername(e.target.value)}
        />
        <br />
        <input
          type="password"
          placeholder="Password"
          onChange={handleFirstEntryPasswordChange}
        />
        <br />
        <input
          type="password"
          placeholder="Repeat Password"
          onChange={handleSecondEntryPasswordChange}
        />
        <br />
        <button
          type="button"
          className="btn btn-secondary"
          id="login-btn"
          onClick={handlingUserInput}
        >
          Register
        </button>
        <a href="#">Login</a>
      </div>
    </>
  );
}
export default RegisterPage;
